#+title: Clojure CDK Example

This is an example project for CDK development with Clojure.

The `cdk.json` file tells the CDK Toolkit how to execute your app.

** Stack

This example systhesises an SQS Queue and an SNS Topic and adds a
subscription for the topic

** Useful commands

 * `clj -M:test`     Run Tests
 * `cdk ls`          list all stacks in the app
 * `cdk synth`       emits the synthesized CloudFormation template
 * `cdk deploy`      deploy this stack to your default AWS account/region
 * `cdk diff`        compare deployed stack with current state
 * `cdk docs`        open CDK documentation

** How it works

[Integrant](https://github.com/weavejester/integrant) is the main tool behind this setup.

CDK Java depends on =software.amazon.awscdk.App= instance and related
=software.amazon.awscdk.Stack= instances

Integrant  is used to manage the dependencies between them. The following
is the configuration used by the integrant system.

#+begin_src clojure
(def config
  {:app/instance {}
   :topic/stack  {:app (ig/ref :app/instance)
                  :id  "TopicStack"}
   :app/synth    {:app    (ig/ref :app/instance)
                  :stacks [(ig/ref :topic/stack)]}})
#+end_src

You can add more stacks to the =:stacks= vector in =app/synth=

Refer CDK Java documentation for more https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-java.html#java-running

Enjoy!

** License
Copyright © 2023 Deepu Mohan Puthrote

Distributed under the MIT License.
